name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
        architecture: x64
    - run: pip install nox>=2024.10.9
    - run: pip install poetry<2.0.0
    - run: nox --sessions tests-3.10 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
